AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Lambda to generate pre-signed URLs for S3 uploads.

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,OPTIONS,POST'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  GeneratePresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: generate-presigned-url
      Handler: index.handler
      Runtime: nodejs18.x
      CodeUri: lambda
      Timeout: 10
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: s3:PutObject
              Resource: arn:aws:s3:::image-bucket-owl-preschool/uploads/*
      Environment:
        Variables:
          BUCKET_NAME: image-bucket-owl-preschool
          ALLOWED_ORIGIN: http://owl-preschool-host.s3-website.us-east-2.amazonaws.com
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /generate-presigned-url
            Method: POST
            RestApiId: !Ref ApiGateway

  ListFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-files
      Handler: list-files.handler
      Runtime: nodejs18.x
      CodeUri: lambda
      Timeout: 10
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: s3:ListBucket
              Resource: arn:aws:s3:::image-bucket-owl-preschool
            - Effect: Allow
              Action: s3:GetObject
              Resource: arn:aws:s3:::image-bucket-owl-preschool/uploads/*
      Environment:
        Variables:
          BUCKET_NAME: image-bucket-owl-preschool
          ALLOWED_ORIGIN: http://owl-preschool-host.s3-website.us-east-2.amazonaws.com
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /list-files
            Method: GET
            RestApiId: !Ref ApiGateway

  GetDownloadUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-download-url
      Handler: get-download-url.handler
      Runtime: nodejs18.x
      CodeUri: lambda
      Timeout: 10
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: 
                - s3:GetObject
                - s3:ListBucket
              Resource: arn:aws:s3:::image-bucket-owl-preschool/uploads/*
      Environment:
        Variables:
          BUCKET_NAME: image-bucket-owl-preschool
          ALLOWED_ORIGIN: http://owl-preschool-host.s3-website.us-east-2.amazonaws.com
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /download-url
            Method: GET
            RestApiId: !Ref ApiGateway